"""
Django settings for hmmtuf project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from .config import BASE_DIR
from .config import DEBUG
from .config import USE_CELERY
from .config import DATABASES
from .config import SESSION_COOKIE_SECURE
from .config import CSRF_COOKIE_SECURE
from .config import ALLOWED_HOSTS
from .config import STATIC_URL
from .config import STATIC_ROOT
from .config import STATICFILES_DIRS
from .config import MEDIA_URL
from .config import MEDIA_ROOT
from .config import USE_DJANGO_EXTENSIONS

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'y=ujo$_)gjwj$*k!v@2ihj@u)s0od%37)m6m)01)k6pc0siqsg'


# Application definition
INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django_plotly_dash.apps.DjangoPlotlyDashConfig',
]

# if we have django extensions then use it
if USE_DJANGO_EXTENSIONS:
    INSTALLED_APPS.append('django_extensions')


# HMMTuf specific applications
INSTALLED_APPS.append('hmmtuf_home')
INSTALLED_APPS.append('file_loader')
INSTALLED_APPS.append('hmmtuf_compute')
INSTALLED_APPS.append('hmm_creator')
INSTALLED_APPS.append('bed_comparator')
INSTALLED_APPS.append('login')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hmmtuf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['%s/templates/' % BASE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hmmtuf.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
